#!/bin/bash -e
#
# Build stat-update from source and then package it up with FPM.
#
# Authors:
#   <adam@opscode.com>
#   <shk@linux.com>
#
# This script works on Ubuntu, and maybe on Debian.

set -v

make clean

sudo apt-get install ragel

mkdir -p tmp/usr/local/bin/
mkdir -p tmp/etc/service/stat-update

make

strip -g stat-update
cp stat-update tmp/usr/local/bin
cp runit/run tmp/etc/service/stat-update/

bundle exec fpm -s dir -t deb \
  -n stat-update -v 1.1.0 --iteration 1 \
  -C tmp \
  .
